# Use r-base:4.4.2 as the base image
FROM r-base:4.4.1

# Set the working directory
WORKDIR /usr/src/app

# Install system dependencies, including g++-12 and libgfortran-12-dev
RUN apt-get update && apt-get install -y \
    gfortran \
    libgfortran-12-dev \
    libcurl4-openssl-dev \
    libssl-dev \
    libxml2-dev \
    libcairo2-dev \
    libxt-dev \
    libharfbuzz-dev \
    libfribidi-dev \
    libfreetype6-dev \
    libpng-dev \
    libjpeg-dev \
    libtiff5-dev \
    libwebp-dev \       
    pkg-config \
    libfontconfig1-dev \
    libzmq3-dev \
    libhdf5-dev \
    build-essential \
    wget \
    bzip2 \
    ca-certificates \
    curl \
    git \
    &&  rm -rf /var/lib/apt/lists/* \
    && apt-get clean
   
# Copy renv.lock and renv/ folder first for caching
COPY renv.lock renv.lock
COPY renv/ renv/

# Install renv
RUN R -e "install.packages('renv')"

# Restore R environment
RUN R -e "renv::restore(lockfile = 'renv.lock', prompt = FALSE)"

# Copy your R project files (including renv.lock)
COPY . .
