FROM r-base:4.5.1

# Set the working directory
WORKDIR /usr/src/app

#install system dependencies
RUN apt-get update && apt-get install -y \
    gfortran \
    libcurl4-openssl-dev \
    libssl-dev \
    libxml2-dev \
    libcairo2-dev \
    libxt-dev \
    libharfbuzz-dev \
    libfribidi-dev \
    libfreetype6-dev \
    libpng-dev \
    libjpeg-dev \
    libtiff5-dev \
    libwebp-dev \
    libgit2-dev \ #added this package as gert depends on it
    libglpk-dev \ #added this one as igraph depends on it
    pandoc \ #added pandoc as required by knitr, pkgdown, rmarkdown
    pkg-config \
    libfontconfig1-dev \
    libhdf5-dev \
    build-essential \
    wget \
    ca-certificates \
    curl \
    git \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean

# (Optional) Install renv so that it's already available in base R.
# This step is not strictly required: renv can auto-install itself on the fly
# if you prefer. But having it pre-installed often avoids potential bootstrapping errors.
RUN R -e 'install.packages("renv", repos="https://cloud.r-project.org")'

# Optionally set a default environment variable for the renv cache location.
# This can also be set/overridden at runtime; so you can leave this out if you prefer.
ENV RENV_PATHS_CACHE=/renv/cache

# By default, we will start an R session in "vanilla" mode so the renv autoloader
# doesn't try to install renv behind the scenes. We’ll manage it ourselves.
# ENTRYPOINT ["R", "--vanilla"]